"""Rebalance node — turns compliance findings into concrete, advisor-approvable trades.

This is what makes the agent *advise*, not just review: when compliance flags a problem
(a restricted holding, an over-concentrated issuer), it proposes specific trades that
bring the portfolio back within policy, with the math computed from the graph (never
generated by the model). Runs only when there's something to fix; the trades flow into
the briefing and are part of what the advisor approves at the human-in-the-loop gate.
"""
from __future__ import annotations

from .. import advice, audit
from ..state import AdvisorState


def rebalance_node(state: AdvisorState) -> dict:
    client_id = state.get("client_id", "")
    status = state.get("compliance_status", "pass")
    if not client_id or status == "pass":
        return {"rebalance": {}, "trace": [{"node": "rebalance", "trades": 0}]}

    plan = advice.propose_rebalance(client_id)
    audit.log("rebalance_proposed",
              {"n_trades": len(plan["trades"]), "compliant_after": plan["compliant_after"]},
              run_id=client_id)
    return {"rebalance": plan,
            "trace": [{"node": "rebalance", "trades": len(plan["trades"]),
                       "compliant_after": plan["compliant_after"]}]}
